default_platform(:ios)

platform :ios do
  desc "Archive and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "4LV25PP896",
      issuer_id: "76aeceb6-cdd5-4b5f-94e1-692c0dc9cb8f",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_4LV25PP896.p8")
    )
    build_app(
      scheme: "Allotment",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates -authenticationKeyPath #{File.expand_path("~/.appstoreconnect/private_keys/AuthKey_4LV25PP896.p8")} -authenticationKeyID 4LV25PP896 -authenticationKeyIssuerID 76aeceb6-cdd5-4b5f-94e1-692c0dc9cb8f"
    )
    upload_to_testflight(api_key: api_key)
  end
end
