default_platform(:ios)

platform :ios do
  desc "Archive and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Allotment",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end
